# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [7]:
#Code comes here
arr2 = np.tile(1, 10)
print(arr2)

arr3 = np.arange(0, 21, 1, dtype="int")
print(arr3)

arr6 = np.ones((1, 5, 5))
print(arr6)


[1 1 1 1 1 1 1 1 1 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [11]:
# Code comes here
arr8 = np.random.randn(3, 3, 3)
print(arr8)

arr8a = arr8.reshape(27)
print(arr8a)

[[[-0.57460754 -0.59878317  0.30969363]
  [ 2.92758863  0.30659528  1.70679796]
  [ 2.09722704 -0.20611145 -0.65771895]]

 [[ 0.09609571  0.69350996 -0.23576692]
  [-2.57350507  0.53626345 -2.63947213]
  [ 1.27578324 -0.21473941  0.38635971]]

 [[-1.03804131 -0.10270249 -0.75107767]
  [ 0.29055249  1.41149127  0.00888426]
  [-0.13829703  0.05797651 -2.27148038]]]
[-0.57460754 -0.59878317  0.30969363  2.92758863  0.30659528  1.70679796
  2.09722704 -0.20611145 -0.65771895  0.09609571  0.69350996 -0.23576692
 -2.57350507  0.53626345 -2.63947213  1.27578324 -0.21473941  0.38635971
 -1.03804131 -0.10270249 -0.75107767  0.29055249  1.41149127  0.00888426
 -0.13829703  0.05797651 -2.27148038]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [14]:
# Code comes here
arr10 = np.linspace(0, 10, 20, dtype="int")
print(arr10)

[ 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [27]:
import numpy as np
a = np.arange(1, 17).reshape(4, -1)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [37]:
#Code goes here
print("array")
print(a[0:4, 0:2])

array
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [39]:
# Code come here
print("array")
print(a[1, 0:5])

array
[5 6 7 8]


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [45]:
# Code comes here
import numpy as np

array1 = a
total = np.sum(array1)
print(total)

136


## 2.6 

Calculate the sum of each row in `a`.

In [46]:
# Code comes here
import numpy as np

array1 = a
total_1_axis = np.sum(a, axis=1)
print(f'Sum of elements at 1-axis is {total_1_axis}')

Sum of elements at 1-axis is [10 26 42 58]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [52]:
# Code comes here

print(a)
np.mean(a)
arr10bool = a > 8.5
print(arr10bool)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[False False False False]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [53]:
# Codes comes here
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [54]:
# Code comes here
food_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv", sep=",", header=0, encoding="ISO-8859-1")
food_df.head(10)

country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.10 

How many rows and columns are there in the dataframe?

In [56]:
#Code comes here
print(len(food_df)) 
#and 4 columns

1430


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [65]:
# Code comes here
food_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv", sep=",", header=0, encoding="ISO-8859-1")
food_df.columns = [column.replace(" ", "_") for column in food_df.columns]
food_cnt = food_df.count()
food_mn = food_df.mean()
food_max = food_df.max()
food_min = food_df.min()
food_rang = food_max-food_min
food_stats= pd.Series({"Count": food_cnt, "Mean": food_mn, "Max": food_max, "Min": food_min, "Range": food_rang}).to_frame().transpose()
print(food_stats)

/var/folders/2h/92791q1s1djfc2lgn255v0fh0000gn/T/ipykernel_31844/3991327864.py:5: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  food_mn = food_df.mean()


TypeError: unsupported operand type(s) for -: 'str' and 'str'

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [62]:
# Code comes here
food_min = food_df["Minimum"].min()
print(food_min)


KeyError: 'Minimum'

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here


## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.